### ISSUE TITLE
auto install does not work

### ISSUE THREAD

**Issue by studiokiwik** [PrestaShop/docker#1]
latest (1.6.1.0) doesn't install, starts with installation wizard
1.6.0  somethings going wrong, having Error: "install" directory is missing on start

(Using docker run -ti --name some-prestashop -p 8080:80 -d quetzacoalt/prestashop and docker run -ti --name some-prestashop2 -p 8081:80 -d quetzacoalt/prestashop:1.6.0 to run)

**Comment by Quetzacoalt91** [comment]
Hi @studiokiwik,

By default, the PrestaShop container starts with the installation wizard. If you want to install it automatically, you have to add the parameter `-e PS_INSTALL_AUTO=1` in your command :)

About the tag 1.6.0, I will verify if the content is good. However, it should be able to redirect automatically to the folder *install-dev*.

**Comment by Quetzacoalt91** [comment]
For the tag 1.6.0, the link was wrong. It was related to a wrong tag. I have just updated it, so you can use it again properly.

Best regards
