### ISSUE TITLE
 Package 'php-apc' has no installation candidate

### ISSUE THREAD

**Issue by legithubdeaymeric** [PrestaShop/docker#107]
Hello,

In recent days we have encountered a construction problem on our CI.
The image no longer builds and we have:

`The package 'php-apc' does not have an installation candidate`

Do you have an idea where this may come from?

Thanks

**Comment by kikebeltran** [comment]
Hi guy!

Try to install  php-apcu

`sudo apt-get install php-apc`

BR

**Comment by matks** [comment]
Closing as it seems an answer was found 😉 thanks @kikebeltran
