### ISSUE TITLE
no link option for existing db container

### ISSUE THREAD

**Issue by Dotrar** [PrestaShop/docker#11]
Forgive me if I am mistaken because I am new to docker applications.
I see that you provide an option for an external db through a network IP ( using the e vars ) but would it be better to provide a --link option so that one could link it with an existing db that does not have a network interface?

**Comment by Quetzacoalt91** [comment]
Hi,

Thanks to the `--link` option, you can reach another container without its IP address but its name.
In example, if you have a mysql container linked with `--link mysql`, your database address  will be `mysql`. You do not have to look for its IP address.

Best regards

**Comment by Dotrar** [comment]
ok so the --link option is in there? there wasn't a mention of it in the front page

would it just be --link ourmysqlcontainer:mysql ?

**Comment by Dotrar** [comment]
`--link oursqlcontainer -e DB_SERVER=oursqlcontainer`
seemed to have worked fine.

cheers
