### ISSUE TITLE
Can't install theme

### ISSUE THREAD

**Issue by Loxeno** [PrestaShop/docker#124]
Hi,

I would like to test my new theme.
I use the latest version of this docker (prestashop/prestashop:1.7_7.1-fpm which gave me 1.7.3.2).

When I want to install my theme through "Design > Theme & Logo", I click on "Add new theme".
I don't see any option allowing me to upload the .zip file.
I can't even choose the theme if I uploaded it on my FTP.

I just have this warning :
"Please note that for security reasons, you can only add themes that are being distributed on PrestaShop Addons, the official marketplace."

But, as I understand, this warning only stand for Prestashop Cloud, which is not my case.

Do you have any idea ?

For information, the .env I use :
PS_DEV_MOD=0
PS_HOST_MODE=1 (tried to change it to 0, delete the container and recreate it with docker-compose, nothing happened)
PS_INSTALL_AUTO=1
PS_ERASE_DB=0

By advance, thank you.

**Comment by Quetzacoalt91** [comment]
This issue is clearly caused by `PS_HOST_MODE=1`.
If the error message still occurs, are you sure you properly removed your containers ?

```
docker-compose down -v
```

**Comment by Loxeno** [comment]
Yes, I am sure I have properly deleted the fpm container.

I just installed a new instance with PS_HOST_MODE=0, I can upload my theme, so my problem is resolved (no production, we are only testing right now).

Maybe there must be a parameter in database to change in order to take effect ?

**Comment by Quetzacoalt91** [comment]
Yeah probably, I don't know by heart what are the consequence of this parameter during installation.

Just in case, you won't need to change this value later. It was used by PrestaShop for a cloud environment which restricted some features.
