### ISSUE TITLE
too much redirections & URL error

### ISSUE THREAD

**Issue by KannarFr** [PrestaShop/docker#13]
Hi,

I've got an nginx web server which redirects flow to your docker image (by a proxy_pass), bind by 8080:80 and which contains an apache server.

From default, all href on prestashop are redirecting to localhost:8080, so in the URL parameter i set my server ip (which goes to nginx) and i got an too much redirections error.

When i join my server via his ip on my browser, it works, but href goes to something like localhost:8080/path and to see the real page i have to replace localhost:8080 by my ip, don't where to set the modification. 

When i define the real domain on ps admin interface, i've got an redirection's loop and fail (stopped by browser).

Any idea?

Alex :).

**Comment by aleksander351** [comment]
@KannarFr Hi. Any success? I successfully installed with nginx-proxy, but can not access the site because of the same redirect error.

**Comment by aleksander351** [comment]
Quel dommage. I am still hopeful. Am following this discussion right now: https://github.com/jwilder/nginx-proxy/issues/422

Thanks for your reply!

**Comment by aleksander351** [comment]
I got it working with a mariadb container.

images:
- mariadb
- prestashop/prestashop
- nginx-proxy
- letsencrypt
