### ISSUE TITLE
Database Server Not Found

### ISSUE THREAD

**Issue by michael-nee** [PrestaShop/docker#130]
Get a Database Server Not Found no matter what configuration I use.

I've tried mysql inside container as per instructions and an MySQL Server hosted on azure which I can contact using mysql client and have exposed the correct firewall rules.  I've opened up the ports when running the presta-shop container.  This is the same on docker locally and in VM hosted in cloud provider.

**Comment by matks** [comment]
Hello,

If you are using MySQL 8, I have found issues with it and created a PR to explain in the README how to solve them: https://github.com/matks/docker/blob/321ac61fdc963e4bab426f015968c91bf9295bb3/README.md

**Comment by Quetzacoalt91** [comment]
If the diagnostic from @matks id correct, this issue is fixed by #129.

Please let us know is the issue still occur.
Regards
