### ISSUE TITLE
Adding custom default module to prestashop/prestashop image

### ISSUE THREAD

**Issue by bouchezb** [PrestaShop/docker#131]
Hi,

I tried to add a default module to the docker image prestashop/prestashop and build my custom image
```
FROM prestashop/prestashop:1.7.4.1

# Copy additional modules
COPY modules/mymodule /var/www/html/modules/mymodule

EXPOSE 8080
```
When i build my image everything is OK.
I can see in my image built with GitLab that my module is at the right place.

```
$ docker run -it registry.gitlab.com/my-custom-prestashop:master bash
root@078d79666cdd:/var/www/html# ls -l modules
total 228
drwxr-xr-x  6 root root 4096 Jul 25 23:46 blockreassurance
...
-rw-r--r--  1 root root 1289 Jul 25 23:46 index.php
drwxr-xr-x  8 root root 4096 Aug  1 12:11 mymodule
drwxr-xr-x  3 root root 4096 Jul 25 23:46 pagesnotfound
...
drwxr-xr-x 10 root root 4096 Jul 25 23:46 welcome
```
When i run my container named `my-custom-prestashop` with `docker-compose` (with or without PS_INSTALL_AUTO changes nothing), my module and other ones have been deleted
```
$ docker exec -it my-custom-prestashop bash
root@690648ba3f4f:/var/www/html# ls -l modules
total 224 => THIS HAS CHANGED
drwxr-xr-x  6 root root 4096 Jul 25 23:46 blockreassurance
...
-rw-r--r--  1 root root 1289 Jul 25 23:46 index.php
drwxr-xr-x  8 root root 4096 Aug  1 12:11 mymodule => THIS HAS BEEN DELETED
drwxr-xr-x  3 root root 4096 Jul 25 23:46 pagesnotfound
...
drwxr-xr-x 10 root root 4096 Jul 25 23:46 welcome
```

I checked that the image is the right one with image ID in docker registry and my container.
I cannot figure out why some modules have been deleted.

Notice that if i try to overwrite a file in `src` folder, behaviour is the same.
I think there is a cache somewhere used by docker.
I tried to delete images and use a clean local registry but it's not working.

Do you have any idea on what's wrong ?

Regards.

**Comment by bouchezb** [comment]
Hi, i found a solution to my issue this morning.
I leave a comment for those who would have the same issue.
The `docker_run.sh` script is overwritting content of `/var/www/html` during first startup.

https://github.com/PrestaShop/docker/blob/cc7b18f145c9284f53df8a30b96547b2cfcc13b2/base/config_files/docker_run.sh#L9-L13

According to the cp man page `-n` option tells to not overwrite, but here files in directory are deleted (can't explain it but it is).

```
 -n, --no-clobber
    do not overwrite an existing file (overrides a previous -i option)
```

The solution is to copy file to both `/tmp/data-ps/` and `/var/www/html/` in dockerfile.
Files will be present when container runs first and when docker image is updated.

Regards.

**Comment by Quetzacoalt91** [comment]
Thanks for letting us know how you managed to fix the issue, this will help us to fix future similar issues
