### ISSUE TITLE
Best way to install/enable Xdebug ?

### ISSUE THREAD

**Issue by morfin** [PrestaShop/docker#158]
Hi,
I just noticed the container doesn't come with Xdebug. 

Can somebody please point me to the right direction?

Thanks.

**Comment by khouloudbelguith** [comment]
Hi @morfin,

You can add in your Dockerfile

```
#xdebug
RUN yes | pecl install xdebug \
   && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
   && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
   && echo "xdebug.remote_connect_back=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
   && echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini \
   && echo "xdebug.remote_host=pagamac.docker.local" >> /usr/local/etc/php/conf.d/xdebug.ini
```

I hope this helps you.
Thanks!

**Comment by Quetzacoalt91** [comment]
Hi @morfin,

You can follow @khouloudbelguith instructions for adding xdebug to your image. xdebug is not provided by default as the container may be used for production environment.

**Comment by morfin** [comment]
@khouloudbelguith, @Quetzacoalt91  Thanks a lot.

**Comment by morfin** [comment]
I Just had to specify older xdebug version compatible with PHP 5.6:
pecl install xdebug-2.5.5

**Comment by manfield** [comment]
I think it would be nice to add the XDEBUG option as command parameter.
Did you think about it? would you approve this merge request in case?

**Comment by matks** [comment]
> I think it would be nice to add the XDEBUG option as command parameter and make it be available dynamically.
> Did you think about it? would you approve this merge request in case?

I guess yeah 😄please let me check with @PierreRambaud 

@PierreRambaud I think we would be happy to add optional Xdebug setup into this image ?

**Comment by PierreRambaud** [comment]
Not sure it's a good idea to add xdebug. Docker allows you to create custom Dockerfile with the prestashop image as parent. if we start to add option for a development dependency, we're going to have problems :sweat: 

As @Quetzacoalt91 said, our docker images are designed for production.
This kind of change must be done in the https://github.com/PrestaShop/PrestaShop/blob/develop/docker-compose.yml file or https://github.com/PrestaShop/PrestaShop/blob/develop/.docker/Dockerfile.
