### ISSUE TITLE
Multiboutique is not working due to redirection problem.

### ISSUE THREAD

**Issue by degouville** [PrestaShop/docker#161]
My Prestashop over Docker install in working well but the multiboutique is not working at all.

I activated multiboutique option in the admin and create shops with there proper URL...
<img width="200" alt="Capture d’écran 2019-04-18 à 13 39 21" src="https://user-images.githubusercontent.com/6653988/56358754-e3dca400-61df-11e9-8385-0c5990612cbd.png">

But I get an Error 500 in the front-office :

> Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.
>
> Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
> More information about this error may be available in the server error log.
> 
> Apache/2.4.25 (Debian) Server at preprod.shop.xxx.com Port 80

`sudo docker logs prestashop --since 1` show me this report:
> [Thu Apr 18 05:41:25.861187 2019] [core:error] [pid 16] [client 172.18.0.1:34802] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://preprod.shop.

I can't find what wrong with my Nginx config file:
```
server {
	server_name preprod.shop.xxx.com;

	location / {
		client_max_body_size 32m;
		proxy_buffering off;
		proxy_http_version 1.1;
		proxy_read_timeout 600;
		proxy_send_timeout 600;
		proxy_set_header   Host              $http_host;
		proxy_set_header   Referer           $http_referer;
		proxy_set_header   X-Real-IP         $remote_addr;
		proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
		proxy_set_header   Upgrade           $http_upgrade;
		proxy_set_header   Connection        "upgrade";
		proxy_set_header   X-Forwarded-Proto https;
		proxy_set_header   X-Nginx-Proxy     true;
		proxy_redirect     off;
		proxy_pass         http://prestashop;
		if ($uri != '/') {
			expires 30d;
		}
	}

    listen 80;

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/preprod.shop.xxx.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/preprod.shop.xxx.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
```

The probleme seems to come from the autogenerated .htaccess file...
Please, What can I do to solve this ?

**Comment by mikeartix** [comment]
Ran into the same issue while testing 1.7.7.8-rc, its definitely because of the multi store .htaccess rules. Can anyone solve this? Since the 1.7.7.8 update is focused on multi store..

**Comment by SimonasB88** [comment]
Facing the same issue on `prestashop/prestashop:1.7.7.0-apache` referring to testing in older versions.
Maybe any news on this?
