### ISSUE TITLE
can not acess site from external network

### ISSUE THREAD

**Issue by MasterCATZ** [PrestaShop/docker#163]
Spent a day now trying to get the page to load up from another machine through the modems gateway 

it must connect to the service as it will redirect to the DNS page that does not load 
( ie if I access using direct Ip address ) 

after 10 hrs playing with 1.7 i decided to try older versions

1.4 , would not even create database , 1.5 would not install demo , 1.6 did install , but had same issue 

when I put in the DNS adress for shop url it would try redirecting localhost to a dead end trying to use the DNS 

nothing wrong with my port forwarding I can access all my other running docker containers just fine 

is their some other security setting stopping me from accessing from an external network ? 

[inspect.txt](https://github.com/PrestaShop/docker/files/3168674/inspect.txt)

**Comment by MasterCATZ** [comment]
On back-office Tab "configure -> shop parameters -> friendy URL's = No -> save"
On back-office Tab "configure -> shop parameters -> friendy URL's = Yes -> save"

then it worked ...

**Comment by matks** [comment]
Sorry for late response, sorry we dont provide advanced support for docker images. I close this issue. Seems like you found a solution to your problem.
