### ISSUE TITLE
Prestashop Image 1.4 fails to install: missing installed/index_cli.php

### ISSUE THREAD

**Issue by GarryOne** [PrestaShop/docker#164]
I've tested some prestashop versions (1.6, 1.7) by using docker images which worked well.
However the tag 1.4 has an issue. The container log looks like this:
```
* Renaming install folder as installed ...
* Renaming admin folder as adminPS ...
* Installing PrestaShop, this may take a while ...
Could not open input file: /var/www/html/installed/index_cli.php
warning: PrestaShop installation failed.
```
As you can see, it tries to call the `index_cli.php` which is missing in version 1.4

When I try to access the app in the browser, I get a blank screen with the following error:
`Error: 'install' directory is missing`

**Comment by Quetzacoalt91** [comment]
Hi there, this feature exists in PrestaShop since v1.5, as written in the documentation:

> PS_INSTALL_AUTO=1: The installation will be executed. Useful to initialize your image faster. In some configurations, you may need to set PS_DOMAIN or PS_HANDLE_DYNAMIC_DOMAIN as well. (Please note that PrestaShop can be installed automatically from PS 1.5)

I advise you to reach the installation folder, which is to be in the "installed" folder in your case.

**Comment by GarryOne** [comment]
Thank you.
