### ISSUE TITLE
docker pull prestashop/prestashop:1.6-5.6-apache not found

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/docker#169]
I wanted to do docker pull of version 1.6 but it gives an error.
With versions 1.5 and 1.7 does not happen, is it temporary? or something is wrong?

```
docker pull prestashop/prestashop:1.5-5.6-apache ✔
docker pull prestashop/prestashop:1.7-5.6-apache ✔
docker pull prestashop/prestashop:1.6-5.6-apache                                                                                                                         
Error response from daemon: manifest for prestashop/prestashop:1.6-5.6-apache not found
```

**Comment by Quetzacoalt91** [comment]
Hi there!

Thanks for the feedback. I guess something is missing in the declared tags.

**Comment by Quetzacoalt91** [comment]
Indeed, some tags were lost at the same moment our github link was suddenly obsolete.

I brought back the tags, expect a delay before seeing them available again.

**Comment by davidglezz** [comment]
Works! Thank you
