### ISSUE TITLE
Cannot access Prestashop container from another machine within local network

### ISSUE THREAD

**Issue by Dandry** [PrestaShop/docker#170]
I have followed the [official guide for setting Prestashop using Docker](https://hub.docker.com/r/prestashop/prestashop/) and have successfully run Prestashop along with mysql and docker network. I have no troubles with accessing it from my host, however I would like to expose the container to other machines within my local network. When entering my host's url on another machine along with the port, I get 302 pointing to localhost, which obviously is an invalid address on all the other machines except my host. Following [#113 ](https://github.com/PrestaShop/docker/issues/113) also tried setting the `PS_HANDLE_DYNAMIC_DOMAIN` environment variable to 1 upon container creation, but this results in constant 302 loops on all of my machines, including the host. What am I doing wrong in this case?
Thank you for your help.

**Comment by Numalama** [comment]
Hi,
Not sure if I understand clearly your needs but I have too possible solutions for you.
**If you wan to connect 2 differents machine:**
- You can set up a reverse proxy using nginx.

**If you are on the same host machine, but using multiples docker container:**
- You can refer to an other container using his IP using this command:

`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id`

**Comment by Dandry** [comment]
Hi, thank you for your reply.
I indeed used nginx to set up a reverse proxy, so any request coming on port 80 to my machine got redirected to the Prestashop container. 
Please close this issue, thank you.
