### ISSUE TITLE
Add 1.7.6.1 docker image as this is the latest patch version

### ISSUE THREAD

**Issue by matks** [PrestaShop/docker#174]

**Comment by milovanbgd** [comment]
This is a Dockerfile I am using for 1.7.6.1 with PHP 7.2, so others can build the image until it is released:
[https://gist.github.com/milovanbgd/d000f0a95cb1313bc5fa400e46ae503c](https://gist.github.com/milovanbgd/d000f0a95cb1313bc5fa400e46ae503c)

**Comment by matks** [comment]
@milovanbgd thanks 😄 actually we have the new version now since PR https://github.com/PrestaShop/docker/pull/175

I forgot to close this issue
