### ISSUE TITLE
PS_DEV_MODE and PS_DEV_DEMO configuration doesn't work

### ISSUE THREAD

**Issue by milovanbgd** [PrestaShop/docker#179]
I am using following vars in docker compose yml file:
PS_DEV_MODE=1
PS_DEMO_MODE=0

I also use auto install, which works. After it installs, when I log in, I see debug mode disabled as well as demo content installed instead being clean instance.

Am I setting it right? I tried to set to =true or =false, but same. Using latest 1.7 image.

**Comment by milovanbgd** [comment]
Sure. Here are the files:
[Dockerfile](https://gist.github.com/milovanbgd/d000f0a95cb1313bc5fa400e46ae503c)
[Docker compose](https://gist.github.com/milovanbgd/7b5955e6dc1a340aeb18c9caddefa57d)
[ps.env](https://gist.github.com/milovanbgd/0e349b41f4ddde7b528972a67bcb46d6)

In ps.env there are parameters for PrestaShop. PS_DEV_MODE and PS_DEMO_MODE have no impact, meaning there is demo data after auto install and there is not debug mode on after autoinstall. I can confirm env gets read because install and admin folder are named per PS_ADMIN_FOLDER and PS_INSTALL_FOLDER parameters.

**Comment by PierreRambaud** [comment]
I just try with your configuration.
Everything is working fine, the shop is in debug mode 
![image](https://user-images.githubusercontent.com/1462701/64944666-28dc3380-d86f-11e9-8d91-051271e1c6fe.png)

But for the demo mode, this is something different. 
There is a confusion, if I'm right, the demo mode is a presentation which restrict the backoffice. 
As I understand you want to disable fixtures that are installed during the installation process. 

You need to run the installation command with the argument: 
```
--step=database,theme,modules,addons_modules
```

It's not currently possible with the current installation script:
https://github.com/PrestaShop/docker/blob/master/base/images/7.2-apache/config_files/docker_run.sh

You'll have to rewrite this file.

**Comment by milovanbgd** [comment]
Ah I see, thanks!

**Comment by dlh2** [comment]
If you don't kow a lot of Docker, just create your own docker_run.sh then do this to override base image docker_run.sh

COPY <folder>/docker_run.sh /tmp/
