### ISSUE TITLE
Can't get past database database configuration

### ISSUE THREAD

**Issue by samayo** [PrestaShop/docker#181]
I am new to prestashop, although I have been trying to install it for a week, to no avail. 

I tried this script on a fresh CentOs7 VPS from DigitalOcean. 
```
# create a network for containers to communicate
$ docker network create prestashop-net
# launch mysql 5.7 container
$ docker run -ti --name some-mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
# launch prestashop container
$ docker run -ti --name some-prestashop --network prestashop-net -e DB_SERVER=some-mysql -p 8080:80 -d prestashop/prestashop
``` 

When I navigate to `http://domain.tld:8080` I see the install page, and everything goes as expected until the database configuration stage, as you can see here:

![Capture](https://user-images.githubusercontent.com/5304093/65805842-78800080-e187-11e9-9f14-5ac838f489ab.JPG)

Password is `admin` as described in the readme. But it doesn't work. I don't know what I am missing. 

Quick debugging with `docker logs some-prestashop` shows me this log: ([full log](https://gist.githubusercontent.com/samayo/e69074800bb35a876070d37e560ef23e/raw/add68d554183a2ad4f92e3a3ec537b8074f5a68b/gistfile1.txt))
```
[root@samayo sites]# docker logs some-prestashop

* Reapplying PrestaShop files for enabled volumes ...

* No pre-install script found, let's continue...

* No post-install script found, let's continue...

* Almost ! Starting web server now


* No init script found, let's continue...
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message
````

**Comment by matks** [comment]
> I am new to prestashop, although I have been trying to install it for a week, to no avail.

Sorry to hear that 😢let's see if we can find a solution

Well, it seems your Prestashop app cannot reach the mysql service through the network although a dedicated network has been created.

Maybe you can try to ssh into the app container, install mysql-client and attempt to connect to the mysql container to see what's going on ?

Something like
```bash
$ docker exec -it some-prestashop bash -l
// in container
$ apt-get install mysql-client
// (warning: recent ubuntu versions have modified name to default-mysql-client as it's now a MariaDB and not a MySQL)
// then poke around to see how you can reach it
$ mysql -h HOST -P PORT_NUMBER -u USERNAME -p
```

I'm not sure `127.0.0.1` is valid when using a docker network 🤔

I think you're supposed to use
- either the container name or the network name
- or declare a `hostname` for the mysql container and use it

**Comment by Quetzacoalt91** [comment]
As @matks said, your database server should `some-mysql`, not `127.0.0.1`

**Comment by samayo** [comment]
Sorry guys, I have been very busy and formatted my laptop so it is taking time, please don't close this issue, I will try again in the afternoon, hopefully it works. @matks thanks for your time and effort bro

**Comment by samayo** [comment]
Is there any configuration that isn't mentioned in the readme? I think I might have some missing config. I am running this on a fresh CentOS Linux release 7.7.1908 (Core).

**Comment by samayo** [comment]
I will format and re-check again. Maybe I have messed up with some config

**Comment by matks** [comment]
Closing as I think the issue got stale - feel free to open a new one if needed 😉
