### ISSUE TITLE
[Docker] FPM image should wait for db 

### ISSUE THREAD

**Issue by freechelmi** [PrestaShop/docker#192]
**Is your feature request related to a problem? Please describe.**
When you invoke db and prestashop ( fpm) in a docker-compose , the PS FPM container will exit because the DB is not ready yet 
**Describe the solution you'd like**
the DB connection should be retried at least for 60 seconds.
**Describe alternatives you've considered**

**Additional context**
That is what other project like nextcloud do.

**Comment by freechelmi** [comment]
Any feedback on this ? Shall we propose a solution ?

**Comment by matks** [comment]
> Any feedback on this ? Shall we propose a solution ?

Sorry for late answer, we had some trouble in November and December (very heavy workload and multiple unexpected emergency tasks) so we're quite late in answering github questions 😅 

We already have a waiting step for DB to be ready 🤔(see https://github.com/PrestaShop/docker/blob/master/base/images/7.2-fpm/config_files/docker_run.sh#L16) isn't it enough ?

**Comment by PierreRambaud** [comment]
If you need to wait for database when using docker-compose, have a look on https://github.com/PrestaShop/PrestaShop/blob/develop/docker-compose.yml 
The wait-for-it.sh is here to help to be sure services are up

**Comment by matks** [comment]
Hi, I think the check added [in this PR](https://github.com/PrestaShop/docker/commit/84c965552836e335697f9fe73512fd70f79500ff) solves the issue 🤔 ?
