### ISSUE TITLE
[compose] prestahsop should wait a bit more for mysql

### ISSUE THREAD

**Issue by freechelmi** [PrestaShop/docker#203]
When runing the preshashop container with mysql , prestashop give up waiting for mysql way too soon in https://github.com/PrestaShop/docker/blob/master/base/config_files/docker_run.sh

Please retry for 3 seconds and we shouldn't need any specific mechanism to fix that.

This would avoid using "restart-always" policy

**Comment by PierreRambaud** [comment]
There is a wait-for-it.sh which is used a lot of time in a docker context: https://github.com/vishnubob/wait-for-it

**Comment by freechelmi** [comment]
Thanks , I would rather avoid this kind of hack if possible as it's just a matter of one or 2 seconds here.

**Comment by PierreRambaud** [comment]
It's more about docker containers dependencies workflow, your PrestaShop container shouldn't be able to run without a MySQL container. 

But regarding the docker_run.sh (https://github.com/PrestaShop/docker/blob/master/base/config_files/docker_run.sh#L16) there is already a `sleep 5` :thinking:

**Comment by freechelmi** [comment]
Well when I see this loop , it seems it waits for ever for mysql to answer so the problem is somewhere else it seems.

**Comment by PierreRambaud** [comment]
@freechelmi Do you still have the problem with latest builds?

**Comment by matks** [comment]
Closing as we got no answer, feel free to reopen another issue if needed 😉
