### ISSUE TITLE
if  PS_INSTALL_AUTO=1 the install folder should be removed

### ISSUE THREAD

**Issue by freechelmi** [PrestaShop/docker#204]
In a "Docker"  style , we should delete the install directory after Autoinstall succeeds.

Right now users have to remove it manually to access the admin panel.

**Comment by alexsegura** [comment]
Yes, it's a pain in the ass to have to do this...

For lazy people coming here, this can be done via `docker exec`:

```bash
docker exec -it <name_of_container> rm -rf install
```

From what I see in `docker_run.sh`, it _should_ also be possible to do it via a post-install script. 

https://github.com/PrestaShop/docker/blob/c946db25a0fa6122ebede3f0cd02ca0c1954e8b6/base/config_files/docker_run.sh#L101-L109

So basically people would need to mount a volume `/tmp/post-install-scripts/` containing a script that just does:

```bash
#!/usr/bin/env bash
rm -rf /var/www/html/install
```

**Comment by Quetzacoalt91** [comment]
Note you can also use another value for `PS_FOLDER_INSTALL`, which will rename the install folder and allow you to access the administration panel.

**Comment by alexsegura** [comment]
Yes, but it is a security risk, no?

**Comment by freechelmi** [comment]
I tried the PS_FOLDER_INSTALL=anything on 1.6-5.6 and it does not solve the problem

I guess the post install hook will be necessary anyway here

**Comment by sergioregueira** [comment]
Renaming the directory is security by obscurity; it should have a postinstall script to delete the install directory automatically.
