### ISSUE TITLE
Images for 1.7-7.3 fpm tags are not available in the hub, despite the readme points to them.

### ISSUE THREAD

**Issue by elboletaire** [PrestaShop/docker#213]
In the main readme of the project in the docker hub I can see there should be an image named `1.7-7.3-fpm` and/or `nightly-7.3-fpm`. None of those images exist in the hub, but I can see there are files for them in the repo:

https://github.com/PrestaShop/docker/tree/master/images/1.7-7.3-fpm

You can easily check that they do not exist by using docker pull:

~~~bash
docker pull prestashop/prestashop:1.7-7.3-fpm
# Error response from daemon: manifest for prestashop/prestashop:1.7-7.3-fpm not found: manifest unknown: manifest unknown
docker pull prestashop/prestashop:nightly-7.3-fpm
# Error response from daemon: manifest for prestashop/prestashop:nightly-7.3-fpm not found: manifest unknown: manifest unknown
~~~

**Comment by wapmorgan** [comment]
+1

**Comment by PierreRambaud** [comment]
Woot, thanks a lot for your feedback. I'm on it :+1:

**Comment by PierreRambaud** [comment]
It's ok now, thanks again :wink:
