### ISSUE TITLE
There's no image for version 1.7.6.4

### ISSUE THREAD

**Issue by mcastillof** [PrestaShop/docker#216]
https://hub.docker.com/r/prestashop/prestashop/tags

There's an image for version 1.7.6.3, but not for 1.7.6.4.

**Comment by matks** [comment]
Weird, we did the release
- https://github.com/PrestaShop/docker/pull/210
- https://github.com/PrestaShop/docker/pull/212

**Comment by matks** [comment]
I think it's the `1.7` image. We update it to always target the latest.

**Comment by mcastillof** [comment]
I did a Docker test right now, with tags "1.7" and "latest". Results:

```
image: "prestashop/prestashop:latest"     ->  1.7.6.3
image: "prestashop/prestashop:1.7"        ->   1.7.6.4
```
I'm new with Prestashop and Docker, I was expecting a "1.7.6.4" tag, but as "1.7" points there, I will use that one. Also, shouldn't "latest" be pointing "1.7" or "1.7.6.4" instead of "1.7.6.3"?   

> We update it to always target the latest.

I don't understand if a change was done now, or it was done in the past. Maybe is a matter of time for the change to take effect. 

Feel free to close the issue if this is the intended behavior.

**Comment by PierreRambaud** [comment]
I manage to reproduce the issue, we will have a check as soon as possible.

**Comment by PierreRambaud** [comment]
I improve the build generation. The `latest` will be updated automatically and sync with the `1.7` tag. I also add the 1.7.6.4 tag :wink:

**Comment by PierreRambaud** [comment]
Tell us if everything is ok.

**Comment by mcastillof** [comment]
Ok I have checked it. Latest pointing to 1.7, 1.7 pointing to 1.7.6.4, and 1.7.6.4 tag is available now. I'm closing this,  thanks.
