### ISSUE TITLE
Walkthrough bypass "hack" HTTPs Reverse proxy + docker with "Blocked loading mixed active content" error

### ISSUE THREAD

**Issue by arvanus** [PrestaShop/docker#220]
Hi everybody 
Im at my first Prestashop setup using github source + default docker-compose.yml file running behind a reverse proxy running apache with Let's Encrypt for certificates
My default infra is like this:
```
                  [HTTP]          [HTTPS]
                     `->REDIRECTS-->|
                                     `.
                                      |
                                      v
       [PROXY REVERSE APACHE WITH VALID CERTIFICATE]
                      |
                      v
                      `->[DOCKER:8080]
                            ,-´
                            |
                            v
                 [http://PrestaShop:80]

```
I was getting loads of 

> Blocked loading mixed active content

So I figured a temporary solution to use while I'm learning about PrestaShop :)

First I edited `.docker/docker_run_git.sh` file, to enable "substitute" module for apache adding this line at the beginning:
`  /usr/sbin/a2enmod substitute`
Then I removed old image:
`docker rmi prestashop_prestashop-git`
Edited main .htaccess file, adding this to the end of the file:
```
AddOutputFilterByType SUBSTITUTE text/html
Substitute s|http:|https:|ni

```
Finally:
`docker-compose up`
And that's it 👍 

Like I said, just a temporary (permanent? 😅) solution, but hope that it helps you latter!
Thanks

**Comment by matks** [comment]
> Like I said, just a temporary (permanent? 😅) solution, but hope that it helps you latter!


Thank you for sharing this.

Since topic has not moved since 2020 I close it.
