### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by shellandco** [PrestaShop/docker#227]
Hello,

I would like to change the locale inside the container for french. Is there any variables available to perform that to include in the docker-compose file ?

Thnks for your help

Regards

**Comment by PierreRambaud** [comment]
Everything is in the readme file :wink: 
https://github.com/PrestaShop/docker/blob/master/base/config_files/docker_run.sh#L89
![image](https://user-images.githubusercontent.com/1462701/93769152-b5f06000-fc1a-11ea-9cd8-dc9bca175e18.png)

**Comment by matks** [comment]
Closing the issue as latest message provide accurate informations
