### ISSUE TITLE
README hyperlink in "View license information" redirects to prestashop.com homepage

### ISSUE THREAD

**Issue by awitkutarahil** [PrestaShop/docker#234]
Hello,

In the README for this repository, there is a sentence "View license information for the software contained in this image.".

The hyperlink in this sentence is https://www.prestashop.com/en/osl-license but it actually redirects user to https://www.prestashop.com/en/ . The license information does not seem available anywhere else on prestashop.com

**Comment by matks** [comment]
@awitkutarahil Hi, thanks for the bug report ! I submitted a PR to fix it https://github.com/PrestaShop/docker/pull/237

**Comment by awitkutarahil** [comment]
Thank you @matks 👍
