### ISSUE TITLE
Exited with code 42

### ISSUE THREAD

**Issue by sas-adilis** [PrestaShop/docker#257]
Hi,
After launch docker-compose up and waited for 5-10 seconds, prestashop docker is exiting with code 42

prestashop_1  | 
prestashop_1  | * Another setup is currently running...
testpresta_prestashop_1 exited with code 42

"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 42,
            "Error": "",
            "StartedAt": "2021-03-24T07:13:38.230900832Z",
            "FinishedAt": "2021-03-24T07:13:48.643472612Z"
        },

Do you know how fix that ?

**Comment by PierreRambaud** [comment]
Something failed during the installation process, could you show us your docker compose file in order to be able to reproduce the issue?

**Comment by Engazan** [comment]
same for me with this command "Exited 42"

```shell
docker run -ti --name prestashop --network prestashop-network -e DB_SERVER=some-mysql -p 8080:80 -d -v ${PWD}:/var/www/html/ prestashop/prestashop:latest

```

any fix ?

**Comment by PierreRambaud** [comment]
Could you check these files if they are already here?https://github.com/PrestaShop/docker/blob/master/base/config_files/docker_run.sh#L113

**Comment by Tarekdu13** [comment]
Same issue here using a mac, any help on it ?
PrestashopTEST exited with code 42

**Comment by alisamie97** [comment]
I faced the same issue, it comes with the `PS_INSTALL_AUTO` environment varabile in the `docker-compose.yml`
When I remove it and use manual installation it works fine.

**Comment by bagullana** [comment]
This could be helpful for some people since I didn't find any working solution until now. 
So thanks to @matks, you just need to remove the `install.lock` file from your project.

Then, if you check your prestashop container logs, it should display:

`Copying files from tmp directory ...`

This step is quite long, but just wait for it to finish, and your shop will be available locally.

Hope some people will find it useful :)
