### ISSUE TITLE
HTTP 500 while Installing Addons modules

### ISSUE THREAD

**Issue by JamesRDouglas** [PrestaShop/docker#270]
I followed the instructions from the readme and ran the following three commands:

```
docker network create prestashop-net
docker run -ti --name some-mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
docker run -ti --name some-prestashop --network prestashop-net -e DB_SERVER=some-mysql -p 8080:80 -d prestashop/prestashop:latest
```

But when I got to the store installation stage it failed:

<img src="https://user-images.githubusercontent.com/29376341/124307965-76b74e00-db60-11eb-9e36-19804f565a8b.png" width="500">

I am using Ubuntu 20.04 via WSL2

**Comment by PierreRambaud** [comment]
Unfortunately, the problem doesn't come from the Docker itself, but from the addons.prestashop.com API.
There is nothing we can do :(
