### ISSUE TITLE
Database Server is not found.

### ISSUE THREAD

**Issue by condor13** [PrestaShop/docker#277]
I used Portainer and added a stack. 
`version: "2"
services:
  prestashop:
    image: prestashop/prestashop
    networks:
      myprestashop:
    ports:
      - 8281:80
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    volumes:
      - /srv/dev-disk-by-id-usb-WDC/Config/PrestaShop/src:/var/www/html
      - /srv/dev-disk-by-id-usb-WDC/Config/PrestaShop/src/modules:/var/www/html/modules
      - /srv/dev-disk-by-id-usb-WDC/Config/PrestaShop/src/themes:/var/www/html/themes
      - /srv/dev-disk-by-id-usb-WDC/Config/PrestaShop/src/override:/var/www/html/override
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=password
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=0

  mariadb:
    image: mariadb
    networks:
      myprestashop:
    volumes:
      - /srv/dev-disk-by-id-usb-WDC/Databases/PrestaShop:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      myprestashop:
    links:
      - mariadb:mariadb
    ports:
      - 1235:80
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=password

networks:
    default:
        external:
            name: myprestashop`

All containers running. In the logs of the database container i get "2021-10-06 12:43:50 68 [Warning] Aborted connection 68 to db: 'unconnected' user: 'unauthenticated' host: '192.168.64.3' (This connection closed normally without authentication)"
and in the Install GUI I get "Database Server is not found. Please verify the login, password and server fields (DbPDO)".

![Capture](https://user-images.githubusercontent.com/12913162/136210588-4f4e7f59-569f-4c47-966d-05f52a5af3b4.PNG)
![asd](https://user-images.githubusercontent.com/12913162/136210753-32f15491-34b6-412d-b73f-5da3d52bdc03.png)

Thanks :)

**Comment by matks** [comment]
Closing the issue as it is likely to come from your setup

**Comment by eaprile** [comment]
> I used Portainer and added a stack. `version: "2" services: prestashop: image: prestashop/prestashop networks: myprestashop: ports: - 8281:80 links: - mariadb:mariadb depends_on: - mariadb volumes: - /srv/dev-disk-by-id-usb-WDC/Config/PrestaShop/src:/var/www/html - /srv/dev-disk-by-id-usb-WDC/Config/PrestaShop/src/modules:/var/www/html/modules - /srv/dev-disk-by-id-usb-WDC/Config/PrestaShop/src/themes:/var/www/html/themes - /srv/dev-disk-by-id-usb-WDC/Config/PrestaShop/src/override:/var/www/html/override environment: - PS_DEV_MODE=1 - DB_SERVER=mariadb - DB_USER=root - DB_PASSWD=password - DB_NAME=prestashop - PS_INSTALL_AUTO=0
> 
> mariadb: image: mariadb networks: myprestashop: volumes: - /srv/dev-disk-by-id-usb-WDC/Databases/PrestaShop:/var/lib/mysql environment: - MYSQL_ROOT_PASSWORD=password - MYSQL_DATABASE=prestashop
> 
> phpmyadmin: image: phpmyadmin/phpmyadmin networks: myprestashop: links: - mariadb:mariadb ports: - 1235:80 depends_on: - mariadb environment: - PMA_HOST=mariadb - PMA_USER=root - PMA_PASSWORD=password
> 
> networks: default: external: name: myprestashop`
> 
> All containers running. In the logs of the database container i get "2021-10-06 12:43:50 68 [Warning] Aborted connection 68 to db: 'unconnected' user: 'unauthenticated' host: '192.168.64.3' (This connection closed normally without authentication)" and in the Install GUI I get "Database Server is not found. Please verify the login, password and server fields (DbPDO)".
> 
> ![Capture](https://user-images.githubusercontent.com/12913162/136210588-4f4e7f59-569f-4c47-966d-05f52a5af3b4.PNG) ![asd](https://user-images.githubusercontent.com/12913162/136210753-32f15491-34b6-412d-b73f-5da3d52bdc03.png)
> 
> Thanks :)

Same error when is a step to select database 
![image](https://github.com/PrestaShop/docker/assets/43446674/c8ff56b8-0450-458a-8266-767a6d075819)
