### ISSUE TITLE
PS_HANDLE_DYNAMIC_DOMAIN is not taken into account

### ISSUE THREAD

**Issue by akram** [PrestaShop/docker#28]
The following command in dcker_run.sh seems to have no effect

```
		sed -ie "s/DirectoryIndex\ index.php\ index.html/DirectoryIndex\ docker_updt_ps_domains.php\ index.php\ index.html/g" /etc/apache2/apache2.conf
```

This is because the apache2.conf file coming from docker php apache image has no such directive.

**Comment by Quetzacoalt91** [comment]
Interesting, I guess their config file has changed after I added this line.

Thanks for the information.

**Comment by Quetzacoalt91** [comment]
Hi @akram,

I made a review of the changes to the official PHP repository. Indeed, the directive was not in this file anymore, so I updated the path.

Thanks for your feedback.
