### ISSUE TITLE
Installing ModulesAddons fails.

### ISSUE THREAD

**Issue by Palum12** [PrestaShop/docker#283]
Hey, I am having a trouble installing PrestaShop following official instructions from README. 

>create a network for containers to communicate
docker network create prestashop-net
launch mysql 5.7 container
docker run -ti --name some-mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
launch prestashop container
docker run -ti --name some-prestashop --network prestashop-net -e DB_SERVER=some-mysql -p 8080:80 -d prestashop/prestashop

The error I'm getting is
![image](https://user-images.githubusercontent.com/16270898/144443161-27595ca1-63a3-4217-840a-63eafa17560d.png)

This is a clean install. I tried on 2 different machines on Windows 10 with WSL2 and without any luck.

**Comment by hugofintecture** [comment]
Same issue for me with prestashop 1.6 and prestashop 1.7 today with the auto-installer:
```bash
local-prestashop17 | * Launching the installer script...
local-prestashop17 | Module not installed : ps_accounts
local-prestashop17 exited with code 1
```

**Comment by PierreRambaud** [comment]
Hi and thanks for your report. Unfortunately, it's not related to the docker project but to the PrestaShop project itself and more specifically to the PrestaShop company: https://github.com/PrestaShop/PrestaShop/issues/26838
