### ISSUE TITLE
Typo in /config_files/docker_run.sh

### ISSUE THREAD

**Issue by ziaxdk** [PrestaShop/docker#29]
https://github.com/PrestaShop/docker/blob/master/config_files/docker_run.sh#L19

Change from:

    mysql -h $DB_SERVER -P $DB_PORT -u $DB_USER -p$DB_PASSWD -e "status" > /dev/null 2>&1

to:

    mysql -h $DB_SERVER -P $DB_PORT -u $DB_USER -p $DB_PASSWD -e "status" > /dev/null 2>&1

A space between **-p$DB_PASSWD**
Cannot connect to an external instance of MySql

**Comment by mickaelandrieu** [comment]
Please @ziaxdk, provide a pull request :)

**Comment by ziaxdk** [comment]
https://github.com/PrestaShop/docker/pull/30

**Comment by ziaxdk** [comment]
Done
