### ISSUE TITLE
Volumes doesn't work

### ISSUE THREAD

**Issue by nanard52** [PrestaShop/docker#3]
Hi,

Works ok without volumes

but with it doesn't : -v /var/www/html:/var/www/html 

some folders are created :

drwxr-xr-x 2 root     root     4096 Oct 18 13:20 modules
drwxr-xr-x 2 root     root     4096 Oct 18 13:20 override
drwxr-xr-x 2 root     root     4096 Oct 18 13:20 themes

But : Could not open input file: /var/www/html/install-dev/index_cli.php

Thanks

**Comment by Quetzacoalt91** [comment]
Hi @nanard52,

By linking a folder, you replace the container content by your local one.
In consequence, if there is your folder **/var/www/html**, Docker won't be able to find the file index_cli.php

**Comment by nanard52** [comment]
Hi Quetzacoalt91, 

Thank you for answering. 
Let me ask the question differently.

Would't it better to download the source and extract the files in the linked folder ?
Joomla and Wordpress official dockers work like that.
If directory is empty it's populating the sources.

**Comment by mandaman2k** [comment]
Hi, I would also like to see this feature added, for theme development it is much more easier to add or edit files

Thank you

**Comment by DevNIX** [comment]
+1

**Comment by neolectron** [comment]
+1

**Comment by timactive** [comment]
+1

**Comment by nosykretts** [comment]
+1

**Comment by Quetzacoalt91** [comment]
On this pull-request, the sources are now unzipped when the shop is not installed.

This should fix your issues with empty volumes, even if you link the root of website.
