### ISSUE TITLE
Configuring prestashop single container. Can not find server database (DbPDO)

### ISSUE THREAD

**Issue by enricforn** [PrestaShop/docker#32]
Hi guys,

I ran a new prestashop image through this command:

docker run -ti --name some-prestashop -p 8080:80 -d prestashop/prestashop

Then I tried to configure a new brand shop. When I tried to configure database, it seems cannot find server in that container:

Can not find server database. Please verify the user, password and server fields (DbPDO)

Does start docker container should start mysql service ?

**Comment by Quetzacoalt91** [comment]
Hello,

yep, the container is supposed to start its own mysql server if you write the database server as `127.0.0.1`or `localhost`.

**Comment by enricforn** [comment]
I though default server was 127.0.0.1

**Comment by Quetzacoalt91** [comment]
It is, see https://github.com/PrestaShop/docker/blob/master/Dockerfile.model#L6

**Comment by enricforn** [comment]
Ok then probably I'm doing something wrong ?

I can't install a single server prestashop on my container.

Sorry it's a newbie question and should be to a forum. If you're able to do this close the issue.

**Comment by Quetzacoalt91** [comment]
If you execute the exact command you provided in the first message:

```
docker run -ti --name some-prestashop -p 8080:80 -d prestashop/prestashop
```

please provide the result of the following command:
```
docker logs some-prestashop
```

Best regards

**Comment by enricforn** [comment]
Directly pasted:

* Starting internal MySQL server ...

 /!\ WARNING : The MySQL server will be shortly removed from this container !

 /!\ An external server will be required.
[ ok . Starting MySQL database server: mysqld .
[info] Checking for tables which need an upgrade, are corrupt or were
not closed cleanly..

* Grant access to MySQL server ...

* Almost ! Starting Apache now

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 26 15:18:44.901333 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Mon Sep 26 15:18:44.902501 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.17.0.1 - - [26/Sep/2016:15:18:50 +0000] "GET / HTTP/1.1" 302 226 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:18:50 +0000] "GET /install/ HTTP/1.1" 200 3497 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:18:56 +0000] "POST /install/index.php HTTP/1.1" 302 377 "http://localhost:8080/install/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:18:56 +0000] "GET /install/index.php?step=welcome HTTP/1.1" 200 3389 "http://localhost:8080/install/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:18:59 +0000] "POST /install/index.php HTTP/1.1" 200 6847 "http://localhost:8080/install/index.php?step=welcome" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:19:02 +0000] "POST /install/index.php HTTP/1.1" 200 11873 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:19:04 +0000] "GET /install/index.php?timezoneByIso=true&iso=es HTTP/1.1" 200 384 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:19:30 +0000] "POST /install/index.php HTTP/1.1" 200 3065 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:19:34 +0000] "GET /install/sandbox/anything.php HTTP/1.1" 200 205 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:18:58 +0000] "GET /install/index.php?compile_templates=1&bo=1 HTTP/1.1" 200 298 "http://localhost:8080/install/index.php?step=welcome" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:18:59 +0000] "GET /install/index.php?compile_templates=1&bo=1 HTTP/1.1" 200 298 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:19:04 +0000] "GET /install/index.php?compile_templates=1&bo=1 HTTP/1.1" 200 298 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:18:52 +0000] "GET /install/index.php?compile_templates=1&bo=1 HTTP/1.1" 200 298 "http://localhost:8080/install/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:19:34 +0000] "GET /install/index.php?compile_templates=1&bo=1 HTTP/1.1" 200 298 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
::1 - - [26/Sep/2016:15:19:43 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) (internal dummy connection)"
172.17.0.1 - - [26/Sep/2016:15:18:52 +0000] "GET /install/index.php?compile_templates=1&bo=0 HTTP/1.1" 200 299 "http://localhost:8080/install/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:19:34 +0000] "GET /install/index.php?compile_templates=1&bo=0 HTTP/1.1" 200 299 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:18:58 +0000] "GET /install/index.php?compile_templates=1&bo=0 HTTP/1.1" 200 299 "http://localhost:8080/install/index.php?step=welcome" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:18:59 +0000] "GET /install/index.php?compile_templates=1&bo=0 HTTP/1.1" 200 299 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:19:04 +0000] "GET /install/index.php?compile_templates=1&bo=0 HTTP/1.1" 200 299 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
::1 - - [26/Sep/2016:15:19:46 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) (internal dummy connection)"
::1 - - [26/Sep/2016:15:19:47 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) (internal dummy connection)"
::1 - - [26/Sep/2016:15:19:48 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) (internal dummy connection)"
::1 - - [26/Sep/2016:15:19:49 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) (internal dummy connection)"
::1 - - [26/Sep/2016:15:19:52 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) (internal dummy connection)"
172.17.0.1 - - [26/Sep/2016:15:20:17 +0000] "GET /install/index.php?checkDb=true&dbServer=localhost&dbName=prestashop&dbLogin=root&dbPassword=admin&db_prefix=ps_&clear=0&_=1474903174541 HTTP/1.1" 200 615 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:20:22 +0000] "POST /install/index.php HTTP/1.1" 200 3152 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:20:23 +0000] "GET /install/sandbox/anything.php HTTP/1.1" 200 205 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:20:23 +0000] "GET /install/index.php?compile_templates=1&bo=0 HTTP/1.1" 200 299 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
172.17.0.1 - - [26/Sep/2016:15:20:23 +0000] "GET /install/index.php?compile_templates=1&bo=1 HTTP/1.1" 200 298 "http://localhost:8080/install/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"

**Comment by Quetzacoalt91** [comment]
Yeah, the container log shows the MySQL has started as expected, maybe you write the wrong credentials on the page.

However, please note the internal server is not opened by default, only PrestaShop is able to connect to it.

**Comment by enricforn** [comment]
Right, I have to create prestashop database manually. From my point of view should be interesting to create a default empty prestashop database, in order to use a container for test purposes.

**Comment by Quetzacoalt91** [comment]
This is automatically done when your install PrestaShop automaticaly on the first container start.

However, when you go through the installation process and the database does not exist, PrestaShop is supposed to ask you to create it for you, isn't it ?

**Comment by enricforn** [comment]
Nope

**Comment by enricforn** [comment]
I just created database from prestashop wizard

**Comment by MasterCATZ** [comment]
having same issues can not get it to use external database 

tried database on local system that's running docker and another database on a remote server 

tried Ip address and DNS address details 

do you have a launch example for how to pass the override environments via docker cmd line ? 

docker run -ti --name some-prestashop -p 8080:80 -d prestashop/prestashop

how do we use 

DB_SERVER: 
DB_USER: 
DB_PASSWD: 
DB_PREFIX:
DB_NAME:

**Comment by Quetzacoalt91** [comment]
To override these environment variables, you just have to add in your `docker run` command, before `prestashop/prestashop`:

```sh
-e <YOUR VARIABLE>=<value>
```

And you can add this part as many times as needed.
In example, you can define all you DB credentials this way: `-e DB_NAME=my-database -e DB_USER=superman`.

**Comment by MasterCATZ** [comment]
thanks 

I tried it but still will not connect to my database 

#docker logs externaldb-prestashop

* Waiting for confirmation of MySQL service startup


docker run -e DB_SERVER=aio.fritz.box -e DB_USER=PrestaShop -e DB_PASSWD=PrestaShop -e DB_NAME=PrestaShop -e DB_PREFIX=ps -ti --name externaldb-prestashop -p 8111:80 -d prestashop/prestashop

I would have thought that would work ? 
the local machine name is aio and the router identifies it as aio.fritz.box

**Comment by jmvbxx** [comment]
I'm having the same problem as above:
```
-e DB_SERVER=35.xxx.xxx.1 \
-e DB_USER=root \
-e DP_PASSWD=admin \
-e DB_PREFIX=ps_ \
-e DB_NAME=prestashop \
```
I can access the database from the command line without problem `mysql -u root -h 35.xxx.xxx.1 -p` and am able to see the prestashop database.

Suggestions?

**Comment by Quetzacoalt91** [comment]
Hello,

Is the command `mysql -u root -h 35.xxx.xxx.1 -p` run the container or your host?
If that's another container, you may want to link them or connect them in the same network.

**Comment by jmvbxx** [comment]
Yes, that's correct. `mysql -u root -h 35.xxx.xxx.1 -p` works from the host. I am trying to connect to a database in a Google SQL instance. Here is my complete Docker run command:
```
docker run --name prestashop \
-v prestashop:/var/www/html \
-e PS_DEV_MODE=1 \
-e DB_SERVER=35.xxx.xxx.1 \
-e DB_USER=root \
-e DP_PASSWD=admin \
-e DB_PREFIX=ps_ \
-e DB_NAME=prestashop \
-e PS_INSTALL_AUTO=1 \
-e PS_LANGUAGE=es \
-e PS_COUNTRY=CO \
-d --restart always prestashop/prestashop
```
Am I missing something?

**Comment by jmvbxx** [comment]
I also just confirmed that I can access MySQL from within the container as well.

**Comment by Quetzacoalt91** [comment]
This is probably caused by the typo you made in the param `DP_PASSWD`. It should be `DB_PASSWD`.

**Comment by jmvbxx** [comment]
Doh!!! Thank you so much! I really appreciate the quick responses. Especially for such an old ticket

**Comment by jmvbxx** [comment]
One final question .. I have specified `PS_DOMAIN=prestashop.abc.com` yet I am still getting `AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message`.

Is this correct?

**Comment by Quetzacoalt91** [comment]
Yes, the env variable `PS_DOMAIN` is used only for the PrestaShop installation.
We do not change the Apache config file on the first run, although it would be a nice improvement.

You can safely ignore this message, it won't prevent your web server to work.

**Comment by jmvbxx** [comment]
I'm running nginx reverse proxy and am getting 502 Bad Gateway and thought it might be related. I have several WordPress instances running under the same infrastructure without issue. Any ideas?

**Comment by Quetzacoalt91** [comment]
Perhaps it would be better to open another issue.
Also, check your nginx proxy logs to have more details, the 502 error does not provide much details on the issue. :(

**Comment by jmvbxx** [comment]
You're so right. This issue is clearly closed

**Comment by aleksander351** [comment]
@jmvbxx I had also a 502. It turned out, Prestashop wasn't on the same network as nginx-proxy.

**Comment by aleksander351** [comment]
I am also having this message:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message

I am using a nginx reverse proxy and multiple installations on same server.

It turns out, after a restart of the containers (server maintenance or any other reason), the
IP of the database container is wrong. So I have to manually fix it inside /app/config/parameters.php

Is there no parameter I could set inside docker-compose.yml?
