### ISSUE TITLE
Outdated description on docker hub

### ISSUE THREAD

**Issue by romlly** [PrestaShop/docker#333]
On the prestashop image page description on docker hub, the version 8 is missing.

Currently :

```
Image by PrestaShop version :
1.7, latest
1.6
...
```

but it should be :

```
Image by PrestaShop version :
8, latest
1.7
1.6
...
```

**Comment by matks** [comment]
Hi, the tag `latest` 😉 is the 8 version

**Comment by romlly** [comment]
Hello,

You are right but it's not on the prestashop description page on docker hub :

![Capture d’écran du 2023-05-19 23-43-49](https://github.com/PrestaShop/docker/assets/1822627/74835a0a-a1c4-472d-bcb9-ff6ff714a3bf)

**Comment by llqfront** [comment]
I use 8.03 directly, the interface is very friendly, comfortable to look at, and easy to use

**Comment by YouriT** [comment]
Definitely time to update the docker hub description page, default ps version is like 4y old if you follow the description

**Comment by Quetzacoalt91** [comment]
That's weird, the Readme is supposed to be updated when the one on GitHub is modified.

I copied pasted to make sure it is updated. Thanks for reporting.
