### ISSUE TITLE
Should Composer be included in some images ?

### ISSUE THREAD

**Issue by thomasnares** [PrestaShop/docker#353]
When i use PrestaShop images for module development, i may sometimes need to execute some composer commands. 

Composer not being installed on the images, i have to: 

- install it temporarly
or 
- create a Dockerfile extending the PrestaShop image to add it, and use the Dockerfile created image in my docker-compose stack. 

Should we add Composer to images to avoid that?

**Comment by jokesterfr** [comment]
Hi Thomas,
you are right, development purpose aims at using a different kind of image sometime.
May you be interested by https://github.com/PrestaShop/prestashop-flashlight for this purpose?

**Comment by Quetzacoalt91** [comment]
Hi @thomasnares,

As composer is not needed to prepare PrestaShop in these images, adding it is not planned at this time.

You may do it with a Dockerfile file based on `prestashop/prestashop` as suggested, or as you're using docker composer: add a [composer container](https://hub.docker.com/_/composer) that will have the shop files mounted as a volume.
