### ISSUE TITLE
Prestashop 1.7.2.5 with PHP 7.1

### ISSUE THREAD

**Issue by Lehaa** [PrestaShop/docker#378]
Hello team,

I would like to test a scenario where I'm running Prestashop 1.7.2.5 on Docker with PHP V.7.1

In Dockerhub 1.7.2.5 docker image has php 5.6.40 hardcoded but I cannot find anywhere the Dockerfile for it.

Is there a way I can achieve this or can I find anywhere the Dockerfile used for it with all files etc. ?

**Comment by Quetzacoalt91** [comment]
Hi @Lehaa,

I think the Dockerfile for 1.7.2.5 has been removed a long time ago.
But I see two solutions:

* Run your shop container a first time with the image `prestashop/prestashop:1.7.2.5` and let it start, the files will be copied in `/var/www/html`. Then stop it, replace the image with `prestashop/base:7.1-apache` and you should be running the same version of PrestaShop with the PHP version you expected.
* Build your own Dockerfile by taking an [existing one](https://github.com/PrestaShop/docker/blob/568ec5c46c766fb0993512e3cb5479a7911ec2a0/images/1.7.7.0/7.1-apache/Dockerfile) as example and modifying it for the PrestaShop you expect.
