### ISSUE TITLE
The docker image of ps 1.7.6.1 and 1.7.6.2 and 1.7.6.6 are not existing

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/docker#388]
Hello,

The docker image of PS 1.7.6.1 - 1.7.6.2  and 1.7.6.6 are not existing
![Capture d’écran de 2024-07-04 15-16-41](https://github.com/PrestaShop/docker/assets/24647495/8f253491-7d58-4c6f-9cb6-5e941f8cf71f)

![Capture d’écran de 2024-07-04 15-17-00](https://github.com/PrestaShop/docker/assets/24647495/d0dbcf91-3ee4-41b0-ad2d-e18267c059be)

![Capture d’écran de 2024-07-05 08-38-56](https://github.com/PrestaShop/docker/assets/24647495/b46db303-bca2-4ad2-ac0a-c3066a890099)

**Comment by Quetzacoalt91** [comment]
Images of PrestaShop 1.7.6.1, 1.7.6.2 and 1.7.6.6 have been manually pushed. Can you please double check?

**Comment by nesrineabdmouleh** [comment]
Yess i found them ! thanks
