### ISSUE TITLE
Some apache images are missing

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/docker#391]
Hello,

We need some apache images of :

- 1.7.5.0-7.1-apache  - 1.7.5.0-7.2-apache

- 1.7.5.1-7.1-apache - 1.7.5.1-7.2-apache

- 1.7.5.2-7.1-apache - 1.7.5.2-7.2-apache

- 1.7.6.0-7.1-apache - 1.7.6.0-7.2-apache

- 1.7.6.1-7.1-apache - 1.7.6.1-7.2-apache

- 1.7.6.2-7.1-apache - 1.7.6.2-7.2-apache

- 1.7.6.3-7.1-apache - 1.7.6.3-7.2-apache

- 1.7.6.4-7.1-apache - 1.7.6.4-7.2-apache

- 1.7.6.5-7.1-apache - 1.7.6.5-7.2-apache

- 1.7.6.6-7.1-apache - 1.7.6.6-7.2-apache

- 1.7.6.7-7.1-apache - 1.7.6.7-7.2-apache

**Comment by Quetzacoalt91** [comment]
Images have been manually generated
