### ISSUE TITLE
Docker image of 1.7.0 ~ 1.7.4 on php 7.1 are missing

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/docker#392]
Hello,

We need an image with PHP_VERSION 7.1 for :

- prestashop:1.7.0.0 ~ 1.7.0.6 
- prestashop:1.7.1.0 ~ 1.7.1.2
- prestashop:1.7.2.0 ~ 1.7.2.5
- prestashop:1.7.3.0 ~ 1.7.3.4
- prestashop:1.7.4.0 ~ 1.7.4.4

**Comment by Quetzacoalt91** [comment]
Images have been pushed (i.e `1.7.2.0-7.1-apache`)
