### ISSUE TITLE
install-dev & admin-dev

### ISSUE THREAD

**Issue by nanard52** [PrestaShop/docker#4]
Hi, 

I would like to know if it the default behaviour for the folder to be named  install-dev & admin-dev

Thank you!

**Comment by Quetzacoalt91** [comment]
Hi @nanard52,

No its not a default behavior. We usually use them in a development configuration, as you can see in the GitHub repository of PrestaShop. In a production environment, the install folder is removed and the admin renamed in order to be unguessable.

**Comment by nanard52** [comment]
Hi, 

That would be great, or even an auto generated folder name, that would be given in the console output !

**Comment by Quetzacoalt91** [comment]
Hi @nanard52,

Sorry, I have never updated this issue after a related commit.
Does https://github.com/PrestaShop/docker/commit/4384b87dc93e3e9ad7ac5a402ab04a8f6638cb60 suits your needs ?
