### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by bertofer** [PrestaShop/docker#42]
When using PS_INSTALL_AUTO=1, doing a simple 
`docker run -ti -p 8080:80  prestashop/prestashop` ends up in this error while trying to install the shop:

* Installing PrestaShop, this may take a while ...
Link to database cannot be established: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

Any help on how to solve it? I just want to use it for development purposes, so for us it's ok to have the MySQL inside the same container

**Comment by Quetzacoalt91** [comment]
Hello @bertofer,

Unfortunately, this is caused by the file `app/config/parameters.php` still present in the release package. It contains database credentials which do not work in the automatic installation. 

What you can do once the container has started:
* Open a terminal in the container `docker exec -ti <container_name> bash`
* Delete the following files:
  * `rm app/config/parameters.php`
  * `rm config/settings.inc.php`
* Close and stop your container
* Start your container, you should have the following log:
![capture d ecran 2016-11-11 a 14 48 15](https://cloud.githubusercontent.com/assets/6768917/20216981/fca4da9e-a81d-11e6-8ab0-803a34bc4085.png)

**Comment by bertofer** [comment]
Hi @Quetzacoalt91 thanks for your answer,

Unfortunately we want this to be as automated as possible, as we want to use the shop for testing an integrated service.  We have been able to do so in the 1.6.1.9 image. Is there any way we can automate this?

**Comment by Quetzacoalt91** [comment]
You can make what I explained automatically:

```sh
docker run -tid -p 8080:80 -e PS_INSTALL_AUTO=1 --name prestashop-tester prestashop/prestashop
docker exec prestashop-tester rm app/config/parameters.php
docker exec prestashop-tester rm config/settings.inc.php
docker restart prestashop-tester 
```

But I hope to not have this file in the next release. :)

**Comment by bertofer** [comment]
@Quetzacoalt91 Thanks for your help! I will wait until this files are removed, as for now we can work with 1.6.1.9 and when this gets solved should be straight forward to migrate :)

**Comment by nilsga** [comment]
I tried the trick with removing the `parameters.php` file, and the container initializes and PS 1.7 is successfully installed, but I cannot log into admin with the default admin user and password. Has something changed regarding this as well?

**Comment by Quetzacoalt91** [comment]
Hello,

Nothing should have changed, until you modified the default values by yourself.
I'll check on my side.

**Comment by nilsga** [comment]
I deleted the `parameters.php` file (in an image derived from this one), but not the `settings.inc.php` (seems to not exist until installation has completed) file though. Could that mess up the secret used for hashing the passwords or something?

**Comment by Quetzacoalt91** [comment]
The file `settings.inc.php` is now always empty.

However, all the credentials are stored in `parameters.yml` and in a compiled version in `parameters.php`.

**Comment by nilsga** [comment]
Seems like the `ps_employees` table is empty, for some reason.

**Comment by aleksander351** [comment]
I can not delete
`docker exec prestashop-tester rm /var/www/html/app/config/parameters.php`

Since it rebuilds parameters.php, and is now NULL, instead of an ARRAY.
