### ISSUE TITLE
First docker run

### ISSUE THREAD

**Issue by Prestaspirit** [PrestaShop/docker#5]
Hi,

I do not understand why it is also the first long run, is that you download all the versions?

Thank's

**Comment by Quetzacoalt91** [comment]
Hi @Prestaspirit,

When you run a container for the first time, Docker will look in your local disk if the image exists and will download it from Docker Hub if it does not find it.

As you can see here: https://hub.docker.com/r/prestashop/prestashop/tags/
Each PrestaShop image weights around 250Mb, which can explain this delay.
But do not worry, you do not have every PrestaShop in one image. Each tag has its specific version.

Best regards
