### ISSUE TITLE
PHP [ Upload + Post ] Max Size configuration

### ISSUE THREAD

**Issue by julianxhokaxhiu** [PrestaShop/docker#54]
Hi,

Is it possible to provide a way to configure php.ini with increased values for `upload_max_filesize` and `post_max_size` ? 8MB may not fit various use cases.

Thank you in advance,
Julian

**Comment by Quetzacoalt91** [comment]
Hi @julianxhokaxhiu,

The default values have been increased to 20M. Please note you can manually change these values once your container has started.

The configuration file can be found in /usr/local/etc/php/php.ini.

Best regards
