### ISSUE TITLE
Add mail support

### ISSUE THREAD

**Issue by neshte** [PrestaShop/docker#55]
Is there a reason for not adding in the Dockerfile the installation of:

`apt-get install -y ssmtp`

so the PHP mail() function of PrestaShop can be called without failing?

Or is it failing just on my side?

**Comment by Quetzacoalt91** [comment]
Hello,

**Comment by Quetzacoalt91** [comment]
Hello,

Until now, I do not have plan to add anything related to the mail in our image. But I have a look to your suggestion.
However, in the meanwhile, do you know you can add it by yourself once the container has started ?

```
docker exec -ti <your container name> apt install -y ssmtp
```

Or you can make make your own Dockerfile like this:
```
FROM prestashop/prestashop

RUN apt install -y ssmtp
```

**Comment by neshte** [comment]
I ended up using SMTP, as it was not that easy to add mail() support and also I think this is not a "prestashop" issue, but rather a PHP one...

**Comment by freechelmi** [comment]
Sorry but I'd like to reopen this as most docker images have smtp mail parameters supports ( like nextcloud ) 

This enable the app to be ready to send user details upon start without admin interactions.

I can open a dedicated issue for this if you prefer ...
