### ISSUE TITLE
Enable SSL when autoinstalling

### ISSUE THREAD

**Issue by xmas79** [PrestaShop/docker#56]
It would be useful to add another option to the container to enable SSL during auto installation (with PS_INSTALL_AUTO=1)

**Comment by Quetzacoalt91** [comment]
Why not, but this won't be done in 5 minutes.

As you can see on http://doc.prestashop.com/display/PS15/Installing+PrestaShop+using+the+command+line, there is no option to enable on PrestaShop installation. This would require an additional script in order to modify the database.

**Comment by samherrmann** [comment]
I created an issue in the [PrestaShop issue tracker](http://forge.prestashop.com/browse/BOOM-2775) to have that feature added to the CLI.

**Comment by Thomvaill** [comment]
+1
I am using PrestaShop behind traefik (SSL only) and the setup is impossible without a manual intervention.
It is good news that this option will be available.
In the meantime, I am happy to share this command which is easily scriptable to automate your setup: `docker exec -ti $(docker ps -qf "name=YOUR_PS_CONTAINER_NAME") mysql -h mysql -pYOUR_PASSWORD prestashop -e "UPDATE ps_configuration SET value = 1 WHERE name LIKE 'PS_SSL_ENABLED%';"`

**Comment by Quetzacoalt91** [comment]
Thanks to #152, enabling SSL at installation will be shortly possible.
