### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by dcma95** [PrestaShop/docker#57]
Hello, 
I try to install prestashop 1.7 with a nginx reverse proxy.
I can install the database, set the title of the site but when I try access to the site I always have this error "ERR_TOO_MANY_REDIRECTS" and I can't do anything...

Cordialy,
AM

**Comment by Quetzacoalt91** [comment]
Hello @dcma95,

The main reason I see is the wrong domain registered during the installation process.
If the address used by the customer to reach the shop is not equals the value in database, PrestaShop redirects him to the proper domain.

Try to reach the back-office (the default value is `admin`). Once connected, you should see a warning message saying you are not on the good domain.

Good luck

**Comment by dcma95** [comment]
Hi @Quetzacoalt91,

Thanks I solve the problem, the problem is that the SSL is not enabled in the admin panel.

Cordialy,
AM

**Comment by Quetzacoalt91** [comment]
Thank you @dcma95. Indeed, SSL is not enabled by default on PrestaShop. :)
As you solved the issue, I close this one.

Have a great week end

**Comment by lantirn** [comment]
How to Make,
1. işlem; 
veritabanına gidip,
SELECT * FROM `ps_configuration` WHERE `name` LIKE '%SSL%' 
sorguluyoruz,
Sonra ps_configuration value sunu "1" yapıyoruz
Sonra PS_SSL_ENABLED_EVERYWHERE value sunu "1" yapıyoruz


2. İşlem;
public_html altında yer alan config dizinindeki config-inc.php dosyasının içindeki 

define(‘_PS_SSL_PORT_’, 443); kodun altına aşağıdaki gibi değişikliği yapmalıyız

/* SSL configuration */
define('_PS_SSL_PORT_', 443);
if(isset($_SERVER['HTTP_SSL']))
{ 
$_SERVER['SERVER_PORT']=443; 
$_SERVER['HTTPS']='on'; 
}
