### ISSUE TITLE
Error in 12% of the installation process

### ISSUE THREAD

**Issue by mschez** [PrestaShop/docker#6]
<img width="666" alt="captura de pantalla 2015-10-31 a las 11 59 46" src="https://cloud.githubusercontent.com/assets/7831767/10863238/3bf232c6-7fc7-11e5-84e4-076a494e9b50.png">

I am reading about errors in installation process and I found some approaches about this error, but I do not accomplish solve it. I checked permissions, changed the database, changed max_execution_time... but nothing seems working. Do you have any idea about it?

**Comment by Quetzacoalt91** [comment]
Hi @mschez,

Interesting, can you please tell me which tag you executed and what is your execution context ? (personal parameters ? external or internal database ? etc.)

**Comment by Quetzacoalt91** [comment]
Hi again,

I have been told that the issue does not only appear on a Docker environment.
Because this is a general issue, you should report it on http://forge.prestashop.com

Best regards

**Comment by mschez** [comment]
I don't know the reason about this error, but I solved it with MariaDB instead of MySQL, I'm sure that is a problem with MySQL version or an incompatibility with Prestashop version. I'm sorry for the low information, I hope to help someone.

**Comment by ddelizia** [comment]
If you use mysql 5.6 or mariadb it should work. Mysql 5.7 has changed a bit and I think prestashop is not fully supporting it.
