### ISSUE TITLE
Where are the images stored? 

### ISSUE THREAD

**Issue by PolGuixe** [PrestaShop/docker#60]
Are the product images stored inside the container? It is possible to use S3 as file system -at least for the images-?

**Comment by Quetzacoalt91** [comment]
By default, they are stored in the contained.

If you want to make them available outside the container (and why not in another filesystem), you have to create a volume on this folder.

You can find more information on this page: https://docs.docker.com/engine/tutorials/dockervolumes/

Best regards

**Comment by PolGuixe** [comment]
Thanks! @quetzacoalt91

How do you mount an external filesystem e.g S3? Do you have any good references?

**Comment by Quetzacoalt91** [comment]
Unfortunately, I never had the chance to do it by myself.

But after a small research, I found a tutorial to mount a S3 filesytem on a EC2 instance: https://forums.aws.amazon.com/thread.jspa?messageID=475840

One the filesystem is mounted, you just have to you it as a volume pour Docker instance. :)

**Comment by 6pm** [comment]
If you created container with command from documentation you only get access with ssh. But if you want open your project in editor(such as vscode) you have to reinstall project:
1) remove old container 
2) docker run -ti --name some-prestashop --link some-mysql -e DB_SERVER=some-mysql -p 8080:80 -d -v ~/projects/presta:/var/www/html prestashop/prestashop

P.S. Difference between default command and my version is this option `-v ~/projects/presta:/var/www/html` - it allow you to mount prestashop code folder to this folder in your PC `~/projects/presta`

P.P.S. And I recommend you to use kinematic app - it is handy GUI for docker containers -  

![image](https://user-images.githubusercontent.com/6547379/33801196-dc37b4a6-dd5b-11e7-9429-aef098c3f5d7.png)

**Comment by roest01** [comment]
to answer this question for 1.7 (google first result):
images are stored in `/img` folder of your prestashop installation.
Some images also may stored in `modules` folder for example within `ps_imageslider`

therefore you should mount following volumes:
```
prestashop-config:/var/www/html/app/config 
prestashop-img: /var/www/html/img
prestashop-modules: /var/www/html/modules
```

**Comment by matks** [comment]
Hi, thanks for everybody participating in this issue, I think we got multiple great answers 😉 so I close it.
