### ISSUE TITLE
Update README following removal of MySQL server from image

### ISSUE THREAD

**Issue by samherrmann** [PrestaShop/docker#68]
Now that the MySQL server was removed from the image in bdcde5b25440cfa4378ab7ff4b44972965ee601d, the [important note](https://github.com/PrestaShop/docker#how-to-run-this-image) in the README should be removed. The "how to run this container" should also be updated with an example that includes the linking to the MySQL container.

**Comment by Quetzacoalt91** [comment]
That's right, a pull-request has just been opened for this point: #74 

Thanks for your report
