### ISSUE TITLE
Remove /install and rename /admin when PS_INSTALL_AUTO=1

### ISSUE THREAD

**Issue by samherrmann** [PrestaShop/docker#69]
When attempting to access the PrestaShop back-office following a successful automatic installation, you are faced with the following error:

> For security reasons, you cannot connect to the back office until you have:
> deleted the /install folder
> renamed the /admin folder (e.g. admin3250jyr2e/)
> Please then access this page by the new URL (e.g. http://172.19.0.3/admin3250jyr2e/)

It would be nice if the automatic installation script would take care of this. Perhaps the name that the `/admin` folder should be renamed to could also be passed in through a variable?

**Comment by samherrmann** [comment]
My bad, I forgot that the `PS_FOLDER_ADMIN` and `PS_FOLDER_INSTALL` variables are already available.

**Comment by samherrmann** [comment]
In hindsight though, if the container is used in production, might it be better to let the automatic installation delete the `/install` folder at the end instead of leaving it around under a different name?

**Comment by samherrmann** [comment]
In hindsight though, if the container is used in production, might it be better to let the automatic installation delete the `/install` folder at the end instead of leaving it around under a different nam

**Comment by Quetzacoalt91** [comment]
Hello @samherrmann,

With this image, I would like to cover dev and prod environments. the only compromise I found for the folder install was to allow you to rename it.
As you saw, there are two environment variables available for the install and admin folders. If you change their value, you will be able to access directly the back-office. Then, you can improve the security of your PrestaShop by deleting the folder manually.

```bash
docker exec -ti <your container name> rm -rf <your install folder>
```

**Comment by samherrmann** [comment]
Thanks for the explanation @Quetzacoalt91

**Comment by vaibhav5592** [comment]
please tell me container name

**Comment by vaibhav5592** [comment]
docker exec -ti <your container name> rm -rf <your install folder>

**Comment by Quetzacoalt91** [comment]
It depends on what you chose. :)

Execute `docker ps` to know how it is called.

**Comment by edevil** [comment]
@Quetzacoalt91 what would be the problem with having a flag to delete the "install" folder instead of renaming it?

**Comment by nickosouras** [comment]
so what would one put if they wanted to rename the admin folder?

**Comment by KysiekD** [comment]
I have already installed prestashop and docker and I have the same problem as in first post. Can smbd give example how to change admin folder and delete install folder using PS_FOLDER_ADMIN and PS_FOLDER_INSTALL?
