### ISSUE TITLE
redirect to IP started with 172. in version 1.7.1.1 when visit admin login page

### ISSUE THREAD

**Issue by emanuelb** [PrestaShop/docker#76]
as noted in comment by pipo1000 in https://hub.docker.com/r/prestashop/prestashop/
> I tried prestashop running on Docker on my Linux server while connecting to it from my Windows pc. However when I try to browse on my Windows PC to the Linux server with http://192.168.2.45:8080 the first response I get from Prestashop running within Docker is a redirect to http://172.17.0.2/index.php? which will not work when you are connecting from a remote Windows PC running a browser. Any ideas to fix this?

running: (version: 1.6.1.13)
```
docker run -ti --name prestashop -e DB_SERVER=mysql5 -e DB_USER=root -e DB_PASSWD=pass -e DB_NAME=prestashop16 -e PS_INSTALL_AUTO=1 -e PS_FOLDER_ADMIN=adminlogin -e PS_FOLDER_INSTALL=installremoved -e ADMIN_MAIL=admin@example.com -e ADMIN_PASSWD=password1! -p 8082:80 -d prestashop/prestashop:1.6.1.13
```
will make visiting http://IP:8082/adminlogin/ work, while using the same command with version 1.7.1.1 will return redirect to IP started with 172. that is unresolved (from outside machine).
tested with: Ubuntu desktop as HOST OS. Ubuntu server as guest OS (that run the above docker command)

**Comment by Kenji-K** [comment]
I solved this by setting the environment variable [PS_DOMAIN](https://github.com/PrestaShop/docker/blob/master/Dockerfile.model) to my desired domain (including the port), in your case you might want to try:
-e PS_DOMAIN=192.168.2.45:8080

**Comment by Kenji-K** [comment]
This is probably true of quite a few docker deployments, so you may want to check the readme to add references to this.

**Comment by Quetzacoalt91** [comment]
You are right, the Readme is going to be updated in #78
