### ISSUE TITLE
The prestashop dir must be declared as a volume

### ISSUE THREAD

**Issue by khena** [PrestaShop/docker#77]
Hi here,

It's very dangerous to put the config directory outside a docker volume, because the config/settings.inc.php is used to run installation (and drop mysql database).  For example, I use docker-compose and the automatic installation :

0. I install prestashop and configure it, everything is fine, my database is ok
1. I change something into docker-compose.yml
2. docker-compose up -d recreate the container, preserving volumes (module, override and theme) but restauring system container like the original image
3. docker_run.sh is running and check if config/settings.inc.php exist (spoiler : no)
4. docker_run.sh re-install prestashop (adding admin / install dir, etc.) and if auto install activated, drop et recreate database !

The 3 directories (config, admin and install) must be preserve between restart / recreating. And we can't mount a volume on /var/www/html because modules, override and themes are already volumes into /var/www/html.

I will try to do a quick PR about this. IMAO, we can move the override, modules  and themes outside the /var/www/html  (as volumes) and create symbolic links with the installer (and add a volume on /var/www/html, obviously). What do you think about this solution ?

**Comment by thomas15v** [comment]
I think only `/var/www/html/config` should be declared as volume, but only if it doesn't contain files (which I ain't sure atm). Declaring `/var/www/html` as volume will delete all the prestashop files, I don't think that would be a good idea.

**Comment by Quetzacoalt91** [comment]
This could work, I reapply all the files until the shop is installed. See https://github.com/PrestaShop/docker/blob/master/config_files/docker_run.sh#L11

**Comment by khena** [comment]
@thomas15v if I understand how prestashop work (I'm only a docker expert :p ) you never update the core of the framework, you will always update the 3 volumes (module, override and theme).

But we can't protect the config, admin & install dir because pretashop needs to rename these directories after install.

So I think the only solution is to mount /var/www/html and to detect on docker CMD if prestashop is already installed into the /var/www/html (for example a file exists). If yes, we skip all. If the user restart the container, we will keep the config, adminXXX and the installXXX .

**Comment by khena** [comment]
PR #83 

what do you think about adding a new ENV var PS_ERASE_MYSQL (default 0) only to confirm the mysql erase action?

**Comment by Quetzacoalt91** [comment]
I'm also facing the issue about volumes today, with **busy resources**. I'd need to set the whole `/var/www/html` as a volume.

I'll have a look on your PR.

**Comment by Quetzacoalt91** [comment]
Hello @khena,

With the PR #87 updating all the PrestaShop images, I close this issue as it is almost available on Docker Hub.

Regards
