### ISSUE TITLE
Session mix up behind proxy

### ISSUE THREAD

**Issue by mmendozadelsolar** [PrestaShop/docker#82]
When using a nginx Load balancer, user sessions get mess up.

I get with Tools:GetRemoteAddr(), the ip from the user, but the session dont work

**Comment by khena** [comment]
2 cases :

- If you have a load balancer, you have 2 instances, you need to share the sessions between instances (with memcache, db, etc.). You need to build your own PHP configuration. Check the PHP-apache docker official image.
- If you have only one instance, it's not a docker prestashop issue but only a prestashop issue :)

**Comment by mmendozadelsolar** [comment]
Hi, I fix it with sticky session on Proxy.

Thanks,
