### ISSUE TITLE
Volumes issue with short tags

### ISSUE THREAD

**Issue by khena** [PrestaShop/docker#90]
Hi,

we have an issue with the dir / volumes with this new kind of image :

"Previously in PrestaShop/Docker" :
- Prestashop dosen't manage well the symlinks (modules issues) > @toutantic 
-  @Quetzacoalt91  > Docker Volumes Management cause issue with full dir (/var/www/html/ into a volume)

We will have an issue in this case too if the user pull the "head version" of image. The volume is persistent if the user don't use the -v on update.

Ex :
docker pull prestashop:1.6
... running container 1.6 and a new version of 1.6 image is release ...
docker pull prestashop:1.6
... docker stop / docker rm container ...
docker run container 1.6 < still old volume with old 1.6 prestashop :(

and if the user want to remove the volume, he loose everything (images, data, themes, module)

Conclusion : remove the short/head tags  (1.6 / 1.7) > each build is a specific tag ? I have no other idea :(

**Comment by Quetzacoalt91** [comment]
Hello @khena,

Today I removed the last declaration of a volume on our image.
But this doesn't prevent anybody to use its own volumes. If you need to use the modules folder as a volume for instance, you can still declare in your docker-compose file or by using the `-v` parameter.

These shorts tag are convenient when you do not know exactly on which minor/patch version is the latest release.

**Comment by khena** [comment]
removing the volume solve all the issues :) The user must use his own volume, agree.
