### ISSUE TITLE
Add possibility to install custom (old) PS version number

### ISSUE THREAD

**Issue by comxd** [PrestaShop/docker#98]
Useful for dev/testing. I suggest to reusing the env variable **PS_VERSION** and use for the download link where PS version is currently hardcoded.

**Comment by ma0dubois** [comment]
+1

**Comment by Quetzacoalt91** [comment]
Hello,

You just have to use a tag, when you want a specific version of PrestaShop.
For instance: `prestashop/prestashop:1.7.3.2`

**Comment by ma0dubois** [comment]
Hi,

Yes, but i would like to pull this version: `prestashop/prestashop:1.6.1.18-7.1-fpm`
It's possible ?

**Comment by Quetzacoalt91** [comment]
No, version specific images are only available with Apache.

You may consider using the image `prestashop/base:7.1-fpm`, on which you download the zip you'd like to use.

**Comment by ma0dubois** [comment]
I thought about it, but the time of compilation of my image (with my specific and gitlab-ci), is considerably increased if I have to download myself the version of prestashop and the sub-modules.

**Comment by PierreRambaud** [comment]
It's against the principle of Docker. A container must represent a state of an application.
You need to build the container yourself if you want something specific.
Regards
