### ISSUE TITLE
I've setup Prestashop 1.7.2.2 with PHP 5.6 but I want the 7.0

### ISSUE THREAD

**Issue by daminufe** [PrestaShop/docker#99]
I've followed the tutorial to launch the Prestashop Docker with the PHP 7, by adding the Environment variable `PHP_VERSION=1.7-7.0` set, yet I have the wrong PHP_VERSION on the Admin info page:
```PHP Version: 5.6.31```

I've executed with this command:

```docker run -ti --name my-docker-name -e PHP_VERSION=1.7-7.0 -e PS_DEV_MODE=false -e PS_INSTALL_AUTO=0 -p 8080:80 -d prestashop/prestashop:latest```

Also, I have the PHP Memory Limit of 128 mb, is that ok, or should I change as well?

**Comment by Quetzacoalt91** [comment]
Hello @daminufe,

If you want the PHP 7.0 version, this must be done via the image tag (at the end of the "docker run" command).

Your command should be like this:
`docker run -ti --name my-docker-name -e PS_DEV_MODE=false -e PS_INSTALL_AUTO=0 -p 8080:80 -d prestashop/prestashop:1.7-7.0`

Is the README too confusing about that? We can change it if needed.

**Comment by ADSapozhnikov** [comment]
@Quetzacoalt91 yep,  I think it's necessary. Sent pull request for it https://github.com/PrestaShop/docker/pull/100

**Comment by Quetzacoalt91** [comment]
Thanks @ADSapozhnikov I hope your pull-request will do the job to avoid future mistakes.

As no more changes are requested, I close this issue.
